### PR TITLE
Fix server issues

### LINKED ISSUE #137: Chat Send Message called without authority

### LINKED ISSUE #140: Server can't restart a game

### PR DESCRIPTION
**Pull request by Kayn017**
Close #137 
Close #140

### CODE REVIEW

File: Assets/Scripts/LivlNetworkRoomManager.cs [hunk 1]
```diff
@@ -27,5 +27,14 @@ public override void OnRoomServerDisconnect(NetworkConnectionToClient conn)
         }
 
         base.OnRoomServerDisconnect(conn);
+        
+        // TODO : si y'a plus de joueurs, on revient a la scene Room
```
Comment (FranckG28) [inline Assets/Scripts/LivlNetworkRoomManager.cs:31]:
```suggestion
```

**Review by FranckG28 — APPROVED** [review]
amazing :)

**Review by jvondermarck — APPROVED** [review]
